[versions]
kotlin = "2.0.21"
junit = "4.13.2"
gson = "2.11.0"
layoutlib-api = "31.4.2"
layoutlib = "14.0.11"
kxml2 = "2.3.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
layoutlib-api = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "layoutlib-api" }
layoutlib-bridge = { module = "com.android.tools.layoutlib:layoutlib", version.ref = "layoutlib" }
layoutlib-runtime = { module = "com.android.tools.layoutlib:layoutlib-runtime", version.ref = "layoutlib" }
layoutlib-resources = { module = "com.android.tools.layoutlib:layoutlib-resources", version.ref = "layoutlib" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
